# Generated by Django 4.1.2 on 2022-10-22 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0002_pinpointsurl_active_alter_pinpointsurl_shortcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pinpoints_url', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='shortener.pinpointsurl')),
            ],
        ),
    ]
