# Generated by Django 4.1.2 on 2022-10-22 13:06

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_pinpointsurl_active_alter_pinpointsurl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinpointsurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
